x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.0
  env_file:
    - .env
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
    - ../redshift_dbt_transformations:/opt/airflow/dbt
    - /var/run/docker.sock:/var/run/docker.sock   
    - ../redshift_dbt_transformations:/opt/airflow/dbt
    - ~/.dbt:/root/.dbt
    - C:\Users\tbenn\.dbt:/root/.dbt
  user: "${AIRFLOW_UID}:0"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db init &&
      airflow users create --username airflow --password airflow --firstname airflow --lastname airflow --role Admin 
      "


  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres
      - airflow-init

volumes:
  postgres-db-volume: